### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by pullmoll** [nih-at/ckmame#2]
I would like to package `ckmame` for [Void Linux](https://github.com/void-linux/void-packages). May I ask for a release tag? The latest `0.12` and its date is 2015-05-03. The configuration back then was using the tools `automake` and `libtool` instead of `cmake` which is described in `INSTALL.md`.

**Comment by 0-wiz-0** [comment]
Yes, we really should release a new version. Our plan is to do this next week.

**Comment by 0-wiz-0** [comment]
We've released 1.0 this week. Thanks for the nudge!
